### ISSUE TITLE
Implement unit tests targeting web app client

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-edge#135]
### Tasks
- [ ] Implement an example unit test targeting some aspect of the client
- [ ] Document process of running the unit test
- [ ] Create GitHub Actions workflow that runs the unit test
