### ISSUE TITLE
Implement unit tests targeting web app server

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-edge#136]
### Tasks
- [ ] Implement an example unit test targeting some aspect of the server
- [ ] Document process of running the unit test
- [ ] Create GitHub Actions workflow that runs the unit test
