### ISSUE TITLE
Use username/password when accessing Mongo server

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-edge#239]
### Background

The Mongo server does not have authentication enabled. I think it was configured under the assumption that only the web app would be able to access it.

### Problem

On Jetstream2, we will be running the Mongo server in its own container and it will be listening for requests from `0.0.0.0`. As a result, any container on the same Docker network (e.g. Caddy) will be able to access it. Even if we were to reconfigure the Mongo server to listen for requests only from the specific IP address of the web app container, we'd still feel more comfortable with the Mongo server requiring authentication.

### Task

- [ ] Update the web app (code and example config files) to use a username and password to access the Mongo server
- [ ] Update the Docker-related files for the development and production accordingly
- [ ] Work with @mflynn-lanl to configure the SDSC-hosted instance accordingly
- [ ] Configure the Jetstream2-hosted instance accordingly

FYI: @yxu-lanl
