### ISSUE TITLE
Recreate web app VM and automate/document the process (Jetstream2)

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-edge#240]
### Task

- [ ] Recreate the web app VM on Jetstream2
- [ ] Write a script that automates the process
- [ ] Document the process

Work with @mflynn-lanl to understanding the requirements around UIDs/GIDs.

Store the content related to this ticket, in: https://github.com/microbiomedata/nmdc-edge/tree/main/docs

**Comment by ssarrafan** [comment]
This is a new issue (3 days ago), checkboxes aren't checked, will move to the new sprint.  @eecavanna
